# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnser" do
  version "2.0.0-rc.1"

  on_macos do
    on_arm do
      sha256 "3e0be988d25c188f09bcab881d122bbbb1afa99be8786d55a509ad7d17897296"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bb426762c8ca3b635506166f37e27a30b9b3fc6998801a730e6238cd1c5781de"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d544502222d332ae4c664d096b1806fe06d9b533ce765851f0b3aab91299f444"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a85c444e366f368ace9349576ffc04998e625cdf7667e152d823f1e205dbb84"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dnser"
  desc "Local domains, TLS and dev-server orchestration"
  homepage "https://github.com/SDK-E/dnser"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "caddy",
      "mkcert",
      "process-compose",
    ]

  binary "dnser"

  uninstall launchctl: [
      "enterprises.sdk.dnser",
    ],
    delete: [
      "~/.dnser",
    ]

  zap delete: [
      "~/.dnser",
    ]

end
