# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnser" do
  version "2.0.0-rc.4"

  on_macos do
    on_arm do
      sha256 "de55c72aedb5f81a7b2cc439618df093850ca619d7644b63c896a48f9f7efa0d"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "74c2947a589101f8c760846f870bd8161d4699ca8a09ae55d8bc047fb67d5970"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "82afc5f58e7cd2c8a3a56f4824a295ac9befb071d3452326bd3d41fcb6a04357"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f4a324c8bbcfce817b24ed3990de0f4b9e7f9886da582c7e7957a987da24a98b"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dnser"
  desc "Local domains, TLS and dev-server orchestration"
  homepage "https://github.com/SDK-E/dnser"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "caddy",
      "f1bonacc1/tap/process-compose",
      "mkcert",
    ]

  binary "dnser"

  zap launchctl: [
      "enterprises.sdk.dnser",
    ],
    delete: [
      "~/.dnser",
    ]

end
