# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnser" do
  version "2.0.0-rc.3"

  on_macos do
    on_arm do
      sha256 "bc68ff3e0db2cd9e02e36326edfd1fc3c4b629bef41475d1d8a50ad416f75b32"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8704bb51a4d1f4eb9d144abf9f4ce76862b0e501e850485e0c5a345f18b86884"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "444ce453d77e83d75f1362f37b06c88d7790f37abd028dba48c428c908f0f6a4"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d016742b00cdb5b6839317d0c6ed53a9e8f2ce8a6fc7460ec3d91828999bff9"
      url "https://github.com/SDK-E/dnser/releases/download/v#{version}/dnser_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dnser"
  desc "Local domains, TLS and dev-server orchestration"
  homepage "https://github.com/SDK-E/dnser"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "caddy",
      "f1bonacc1/tap/process-compose",
      "mkcert",
    ]

  binary "dnser"

  # no uninstall stanza: brew runs it on every UPGRADE — purging ~/.dnser
  # would destroy user journals/state. Full purge is opt-in via --zap.
  zap delete: [
      "~/.dnser",
    ],
    launchctl: [
      "enterprises.sdk.dnser",
    ]

end
